location:
  latitude: -38.7183
  longitude: -62.2666
  name: "Bahía Blanca"
  timezone: "America/Argentina/Buenos_Aires"

database:
  retention_days: 30

api:
  open-meteo:

    ensemble_metadata:
      bom_access_global_ensemble: "https://ensemble-api.open-meteo.com/data/bom_access_global_ensemble/static/meta.json"
      gem_global: "https://ensemble-api.open-meteo.com/data/cmc_gem_geps/static/meta.json"
      icon_global: "https://ensemble-api.open-meteo.com/data/dwd_icon_eps/static/meta.json"
      ecmwf_ifs025: "https://ensemble-api.open-meteo.com/data/ecmwf_ifs025_ensemble/static/meta.json"
      ecmwf_aifs025: "https://ensemble-api.open-meteo.com/data/ecmwf_aifs025_ensemble/static/meta.json"
      gfs025: "https://ensemble-api.open-meteo.com/data/ncep_gefs025/static/meta.json"
      ukmo_global_ensemble_20km: "https://ensemble-api.open-meteo.com/data/ukmo_global_ensemble_20km/static/meta.json"

    ensemble_url: "https://ensemble-api.open-meteo.com/v1/ensemble"

models_used:
  - gfs025
  - bom_access_global_ensemble
  - gem_global
  - icon_global
  - ecmwf_ifs025
  - ecmwf_aifs025
  - ukmo_global_ensemble_20km

forecast_hours: 72